QuanLyTS/QuanLyTS/Models/tblTaiSan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTaiSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTaiSan()
        {
            this.tblChiTietChuyens = new HashSet<tblChiTietChuyen>();
            this.tblChiTietPhieuMuons = new HashSet<tblChiTietPhieuMuon>();
            this.tblChiTietPhieuTras = new HashSet<tblChiTietPhieuTra>();
            this.tblKhoTaiSans = new HashSet<tblKhoTaiSan>();
            this.tblNoiSuDungTaiSans = new HashSet<tblNoiSuDungTaiSan>();
        }

        [Required(ErrorMessage = "Mời nhập mã tài sản")]
        public string MaTaiSan { get; set; }

        [Required(ErrorMessage = "Mời nhập loại tài sản")]
        public string MaLoai { get; set; }

        [Required(ErrorMessage = "Mời nhập loại tài sản")]
        public string TenTaiSan { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string XuatXu { get; set; }
        public string ThoiGianBaoHanh { get; set; }
        public string DonViTinh { get; set; }
        public string GhiChu { get; set; }
        public string SerialNumber
        {
            get; set;
        }
        
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayMua { get; set; }
        public Nullable<int> MaDuAn { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int Soluong { get; set; }
        public string MaDonVi { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayBanGiao { get; set; }
        public double NguyenGia { get; set; }
        public byte[] Image { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayDuKien { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayBaoDuong { get; set; }
        public string LoaiBaoDuong { get; set; }
        public Nullable<double> SoTien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietChuyen> tblChiTietChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuMuon> tblChiTietPhieuMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuTra> tblChiTietPhieuTras { get; set; }
        public virtual tblDonVi tblDonVi { get; set; }
        public virtual tblDuAn tblDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKhoTaiSan> tblKhoTaiSans { get; set; }
        public virtual tblLoaiTaiSan tblLoaiTaiSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoiSuDungTaiSan> tblNoiSuDungTaiSans { get; set; }
        public virtual tblTinhTrang tblTinhTrang { get; set; }

        public List<tblTaiSan> ListAssets_Grid { get; set; }
        public System.Web.Mvc.SelectList ListGroupAssets { get; set; }
        public string GroupAssetId { get; set; }
    }
}

QuanLyTS/QuanLyTS/Controllers/tblTaiSansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyTS.Models;
using PagedList;
using System.Globalization;
using System.Configuration;
using System.Data.SqlClient;
using ClosedXML.Excel;
using System.IO;

namespace QuanLyTS.Controllers
{
    public class tblTaiSansController : Controller
    {
        private QuanLyTSEntities db = new QuanLyTSEntities();

        // GET: tblTaiSans
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var tblTaiSans = db.tblTaiSans.Include(t => t.tblLoaiTaiSan);
            if (!String.IsNullOrEmpty(searchString))
            {
                tblTaiSans = db.tblTaiSans.Where(s => s.TenTaiSan.Contains(searchString)
                                       || s.MaTaiSan.Contains(searchString));
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(tblTaiSans.OrderBy(a => a.MaTaiSan).ToPagedList(pageNumber, pageSize));
        }

        // GET: tblTaiSans/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTaiSan tblTaiSan = db.tblTaiSans.Find(id);
            if (tblTaiSan == null)
            {
                return HttpNotFound();
            }
            return View(tblTaiSan);
        }
        public ActionResult TongHopTaiSan()
        {
            ViewBag.NhomTS = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name");
            tblTaiSan _model = new tblTaiSan();    
            _model.ListGroupAssets = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name");
            return View(_model);
            
        }
        [HttpPost]
        public ActionResult TongHopTaiSan(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTaiSan _model = new tblTaiSan();
            ViewData["ID"] = id;
            var tblTaiSans = db.tblTaiSans.Where(t => t.MaLoai == id).ToList();
             _model.MaLoai = id;
             _model.GroupAssetId = db.tblLoaiTaiSans.Where(t => t.MaLoai == id).FirstOrDefault().GroupAssetId;          
            _model.ListGroupAssets = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name", _model.GroupAssetId);          
            _model.ListAssets_Grid = tblTaiSans.ToList();
            return View(_model);
          }
        public ActionResult TaiSanTheoKho()
        {
            var lst_Kho = db.tblKhoLuuTrus.ToList();
            var model = new ThongKeMODEL()
            {
                lst_Khos = lst_Kho,
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult TaiSanTheoKho(string id)
        {
            var kholuutru = db.tblKhoLuuTrus.Single(a => a.MaKho == id);
            var Kho = kholuutru.tblKhoTaiSans.Where(t => t.MaKho == id).ToList();
            var taisan = db.tblTaiSans.ToList();

            var lst_Kho = db.tblKhoLuuTrus.ToList();


            var model = new ThongKeMODEL()
            {
                lst_Khos = lst_Kho,
                tblKho = Kho,
                tblTaiSan = taisan,
                kholuutrus = kholuutru,
            };

            return View(model);
        }
        public ActionResult TaiSanTheoNoiSD()
        {
            var listDonvi = new List<tblDonVi>();
            ViewBag.MaDonVi = new SelectList(db.tblDonVis, "MaDonVi", "TenDonVi");
            ViewData["CountDonvi"] = 0;
            return View();
        }

        [HttpPost]
        public ActionResult TaiSanTheoNoiSD(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewData["ID"] = id;
            var tblTaiSans = db.tblTaiSans.Where(t => t.MaDonVi == id).ToList();
            ViewBag.MaDonVi = new SelectList(db.tblDonVis, "MaDonVi", "TenDonVi", id);
            ViewData["CountDonvi"] = tblTaiSans.Count;
            return View(tblTaiSans.ToList());

        }

        public ActionResult TaiSanDieuChuyen()
        {
            var noisd = db.tblNoiSuDungTaiSans.ToList();
            var model = new TaiSanDieuChuyen()
            {
                noisds = noisd,
            };
            return View(model);
        }
        // GET: tblTaiSans/Create
        public ActionResult Create()
        {
            ViewBag.NhomTS = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name");
            ViewBag.MaDonVi = new SelectList(db.tblDonVis, "MaDonVi", "TenDonVi");
            ViewBag.ListDuAn = new SelectList(db.tblDuAns, "Id", "Name");
            ViewBag.ListStatus = new SelectList(db.tblTinhTrangs, "StatusId", "Name");
            return View();
        }

        //Action result for ajax call
        [HttpPost]
        public ActionResult GetTypeAssetByParentId(string parentId)
        {
            var lstTypeAssets = db.tblLoaiTaiSans.Where(item => item.GroupAssetId == parentId);
            SelectList list = new SelectList(lstTypeAssets, "MaLoai", "TenLoai", 0);
            return Json(list);
        }
               
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "MaTaiSan,MaLoai,TenTaiSan,ThongSoKyThuat,NamSX,XuatXu,ThoiGianBaoHanh,DonViTinh,GhiChu,SerialNumber,NgayMua,MaDuAn,StatusId,Soluong,MaDonVi,NgayBanGiao,NguyenGia")] tblTaiSan tblTaiSan)
        {
            if (ModelState.IsValid)
            {
                db.tblTaiSans.Add(tblTaiSan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var errors = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.Exception));
            }

            ViewBag.NhomTS = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name");
            ViewBag.MaDonVi = new SelectList(db.tblDonVis, "MaDonVi", "TenDonVi");
            ViewBag.ListDuAn = new SelectList(db.tblDuAns, "Id", "Name");
            ViewBag.ListStatus = new SelectList(db.tblTinhTrangs, "StatusId", "Name");
            return View(tblTaiSan);
        }

        // [HttpPost]
        public ActionResult GenerateMaTs(string assetTypeCode)
        {
            if (!string.IsNullOrEmpty(assetTypeCode))
            {
                var countTs = (db.tblTaiSans.Where(item => item.MaLoai.Equals(assetTypeCode)).Count() + 1).ToString("000");
                return Json(assetTypeCode + "-" + countTs, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

       
        // GET: tblTaiSans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTaiSan tblTaiSan = db.tblTaiSans.Find(id);
            if (tblTaiSan == null)
            {
                return HttpNotFound();
            }
          

            ViewBag.NhomTS = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name");
            ViewBag.MaDonVi = new SelectList(db.tblDonVis, "MaDonVi", "TenDonVi", tblTaiSan.MaDonVi);
            ViewBag.ListDuAn = new SelectList(db.tblDuAns, "Id", "Name", tblTaiSan.MaDuAn);
            ViewBag.ListStatus = new SelectList(db.tblTinhTrangs, "StatusId", "Name", tblTaiSan.StatusId);


            return View(tblTaiSan);
        }
              
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTaiSan,MaLoai,TenTaiSan,ThongSoKyThuat,NamSX,XuatXu,ThoiGianBaoHanh,DonViTinh,GhiChu,SerialNumber,NgayMua,MaDuAn,StatusId,Soluong,MaDonVi,NgayBanGiao,NguyenGia")] tblTaiSan tblTaiSan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblTaiSan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var errors = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.Exception));
            }

                      

            ViewBag.NhomTS = new SelectList(db.tblGroupAssets, "GroupAssetId", "Name");
            ViewBag.MaDonVi = new SelectList(db.tblDonVis, "MaDonVi", "TenDonVi", tblTaiSan.MaDonVi);
            ViewBag.ListDuAn = new SelectList(db.tblDuAns, "Id", "Name", tblTaiSan.MaDuAn);
            ViewBag.ListStatus = new SelectList(db.tblTinhTrangs, "StatusId", "Name", tblTaiSan.StatusId);


            return View(tblTaiSan);
        }

        // GET: tblTaiSans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTaiSan tblTaiSan = db.tblTaiSans.Find(id);
            if (tblTaiSan == null)
            {
                return HttpNotFound();
            }
            return View(tblTaiSan);
        }

        // POST: tblTaiSans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tblTaiSan tblTaiSan = db.tblTaiSans.Find(id);
            db.tblTaiSans.Remove(tblTaiSan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)

QuanLyTS/QuanLyTS/Views/tblTaiSans/Create.cshtml
@model QuanLyTS.Models.tblTaiSan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thêm mới tài sản</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.tblLoaiTaiSan.GroupAssetId, "Nhóm Tài Sản(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.tblLoaiTaiSan.GroupAssetId, ViewBag.NhomTS as SelectList, "--Chọn Nhóm Tài Sản--", htmlAttributes: new { @class = "form-control", @onchange = "GetTypeAsset(this.value,'');" })

                @Html.ValidationMessageFor(model => model.tblLoaiTaiSan.GroupAssetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoai, "Loại Tài Sản(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                <select id="MaLoai" name="MaLoai" class="form-control" onload="onDropdownChange(this.value);" onchange="onDropdownChange(this.value);"></select>

                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaTaiSan, "Mã tài sản(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.MaTaiSan, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MaTaiSan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenTaiSan, "Tên tài sản(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.TenTaiSan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTaiSan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongSoKyThuat, "Thông số kỹ thuật", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ThongSoKyThuat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongSoKyThuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamSX, "Năm sản xuất", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.NamSX, new { htmlAttributes = new { @class = "form-control", @id = "produce", @placeholder = "Chọn năm sản xuất.." } })
                @Html.ValidationMessageFor(model => model.NamSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.XuatXu, "Nước sản xuất", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.XuatXu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XuatXu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiGianBaoHanh, "Thời gian bảo hành", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ThoiGianBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGianBaoHanh, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, "Đơn vị tính", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, "Số serial", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soluong, "Số lượng(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NguyenGia, "Nguyên giá(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.NguyenGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguyenGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, "Ngày mua(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.NgayMua, new { htmlAttributes = new { @class = "form-control", @id = "buy", @placeholder = "Chọn ngày mua ở đây..." } })
                @Html.ValidationMessageFor(model => model.NgayMua, string.Empty, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "Tình trạng", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.StatusId, ViewBag.ListStatus as SelectList, "--Chọn tình trạng--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDuAn, "Dự án", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.MaDuAn, ViewBag.ListDuAn as SelectList, "--Chọn dự án--", htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.MaDuAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDonVi, "Đơn vị sử dụng(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.MaDonVi, ViewBag.MaDonVi as SelectList, "--Chọn đơn vị--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDonVi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, "Ngày bàn giao(*)", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.NgayBanGiao, new { htmlAttributes = new { @class = "form-control", @id = "handover", @placeholder = "Chọn ngày bàn giao ở đây..." } })
                @Html.ValidationMessageFor(model => model.NgayBanGiao, string.Empty, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-6 col-md-8">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>

    <script type="text/javascript">

        $(document).ready(function () {
                     
            var groupid = $('#MaTaiSan').val();
            var maloai = $('#MaTaiSan').val();

            @if(Model!=null && Model.MaLoai !=null)
            {
                @:GetTypeAsset('@Model.tblLoaiTaiSan.GroupAssetId', '@Model.MaLoai')
                            @:onDropdownChange('@Model.MaLoai')
                        }


            $("#handover").datepicker({ format: 'dd/mm/yyyy', autoclose: true, todayBtn: 'linked' })
            // $("#produce").datepicker({ format: 'dd/mm/yyyy', autoclose: true, todayBtn: 'linked' })
            $("#buy").datepicker({ format: 'dd/mm/yyyy', autoclose: true, todayBtn: 'linked' })
        });


        function onDropdownChange(code) {

            $.ajax({
                url: '@Url.Action("GenerateMaTs", "tblTaiSans")',
                type: "Get",
                data: { "assetTypeCode": code },
                "success": function (data) {
                    if (data != null) {
                        var vdata = JSON.stringify(data).replace(/null/g, '""'); //convert to JSON string
                        //var assetTypeCode = JSON.parse(vdata).slice(1, -1);
                        var assetTypeCode = JSON.parse(vdata);
                        console.log(vdata);
                        $('#MaTaiSan').val(assetTypeCode);
                    }
                }
            });
        }

        function GetTypeAsset(_parentId, maloai) {

            var procemessage = "<option value='0'> Please wait...</option>";
            $("#MaLoai").html(procemessage).show();
            var url = "/tblTaiSans/GetTypeAssetByParentId/";

            $.ajax({
                url: url,
                data: { parentId: _parentId },
                cache: false,
                type: "POST",
                success: function (data) {
                    $('#MaTaiSan').val('');
                    var markup = "<option value='0'>--Chọn loại tài sản--</option>";
                    for (var x = 0; x < data.length; x++) {
                        if (data[x].Value == maloai) {
                            markup += "<option value=" + data[x].Value + " selected>" + data[x].Text + "</option>";
                        }
                        else {
                            markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                        }

                    }
                    $("#MaLoai").html(markup).show();
                },
                error: function (reponse) {
                    alert("error : " + reponse);
                }
            });

        }
        
    </script>
}

<div>
    @Html.ActionLink("Quay về danh sách", "Index")
</div>